# Generated by Django 5.0 on 2023-12-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='municipalidad',
            fields=[
                ('id_munici', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id_project', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.BinaryField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('role', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id_photo', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('photo_path', models.CharField(max_length=200, null=True)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.users'),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id_video', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('video_path', models.CharField(max_length=200, null=True)),
                ('id_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.projects')),
            ],
        ),
    ]
