# Generated by Django 5.0 on 2023-12-10 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='photo_path',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='video_path',
        ),
        migrations.AddField(
            model_name='photos',
            name='uploadedFile',
            field=models.FileField(default='C:/Users/axelh/Downloads/imgxd.jpg', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='id_munici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.municipalidad'),
        ),
        migrations.AddField(
            model_name='videos',
            name='uploadedFile',
            field=models.FileField(default='C:/Users/axelh/Downloads/imgxd.jpg', upload_to='Videos/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tasks.projects'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='videos',
            name='id_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='tasks.projects'),
        ),
    ]
