# Generated by Django 5.0 on 2023-12-14 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_appuser_alter_projects_user_id_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='email',
        ),
    ]
