# Generated by Django 5.0 on 2023-12-15 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_appuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='userrole',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descrip_role', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='id_photo',
            new_name='photo_id',
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='id_project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='id_project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='id_project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='videos',
            old_name='id_video',
            new_name='video_id',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='role',
        ),
        migrations.AddField(
            model_name='appuser',
            name='munici_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.municipalidad'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='role_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.userrole'),
        ),
    ]
