# Generated by Django 5.0 on 2023-12-21 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userrole_rename_id_photo_photos_photo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='user_id',
        ),
    ]
