# Generated by Django 5.0 on 2023-12-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_projects_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='nog',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
