# Generated by Django 5.0 on 2023-12-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_rename_photo_id_photos_id_rename_video_id_videos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videos',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
