# Generated by Django 5.0 on 2023-12-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_municipalidad_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipalidad',
            name='uploadedFile',
            field=models.FileField(default='NULL', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='uploadedFile',
            field=models.FileField(default='NULL', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='uploadedFile',
            field=models.FileField(default='NULL', upload_to='Videos/'),
        ),
    ]
