# Generated by Django 5.0 on 2024-01-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_municipalidad_uploadedfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='munici_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.municipalidad'),
        ),
    ]
