# Generated by Django 5.0 on 2024-01-02 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_appuser_munici_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='nog',
            field=models.CharField(default=1, max_length=50, unique=True),
        ),
    ]
